# AUTOGENERATED! DO NOT EDIT! File to edit: 02_loss.ipynb (unless otherwise specified).

__all__ = ['mse', 'MSE_']

# Cell
from fastai.losses import *
from torch.nn import MSELoss
from fastai.basics import *
from fastai.torch_core import Module

# Cell
#export
def mse(a,b):
    a = a.view(-1)
    b = b.view(-1)
    return ((a-b)**(2)).sum()/a.shape[0]

# Cell
class MSE_(Module):
    def forward(self,a,b):
        a = a.view(-1)
        b = b.view(-1)
        return ((a-b)**(2)).sum()/a.shape[0]